version: "3.9"
services: 
 api:
  restart: always 
  build: .
  ports: 
   - 8080:6001
  environment: 
   - ASPNETCORE_ENVIRONMENT=Development
   - ASPNETCORE_URLS=https://+:6001
   - ASPNETCORE_Kestrel__Certificates__Default__Password=pxl-sec-adv
   - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/Api.pfx
   - STS=https://ventielshop.dubbadub.be:8081
